openapi: 3.0.0
info:
  title: "Crypto Tracker API"
  version: "1.1"
  contact:
    name: Upashan Perera
    email: 200495186@student.georgianc.on.ca
    url: https://upashanperera.000webhostapp.com/
servers:
  - url: https://finalprojectapi-dev.onrender.com 
  - url: http://localhost:3000/api
tags:
  - name: Georgian College
    description: college name
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /cryptos:
    get:
      tags:
        - "Georgian College"
      security:
        - basicAuth: []
      description: Returns a list of cryptos
    
      responses:
        "200":
          description: Unfiltered list of cryptos